### ISSUE TITLE
ProgressSpinner widget remains in memory after dismiss

### ISSUE THREAD

**Issue by arkanoid87** [kivy-garden/garden.progressspinner#2]
If you load and dismiss a ProgressSpinner using basic code like this, the ProgressSpinner disappears from the widget tree but remains referenced in memory and will use the cpu

checked with `python main.py -c kivy:loglevel:trace` and solved by removing the ProgressSpinner
```
[TRACE  ] [Lang        ] call_fn => value=(600.0, 426.92307692307696, 63.07692307692308, 824.4713479746133, 849.4713479746133)
[TRACE  ] [Lang        ] call_fn <kivy.graphics.vertex_instructions.Line object at 0x10c9374a8>, key=circle, value=<code object <module> at 0x10c9514b0, file "<string>", line 14>, '(self.center_x, self.center_y, self._radius,\nself._angle_center + self._angle_start,\nself._angle_center + self._angle_end)'
```

```
<LoadingPopup@ModalView>:
     size_hint: (.4,.3)
     auto_dismiss: False
     BoxLayout:
         orientation: 'vertical'
         padding: 20
         spacing: 10
         ProgressSpinner:
             color: color_blue
             stroke_width: 5
             speed: 2
```

```
def load_function(self, function):
    popup = Factory.LoadingPopup()
    popup.open()

    def callback(p, f, dt):
        f()
        Clock.schedule_once(partial(p.dismiss))

    Clock.schedule_once(partial(callback, popup, function), 0.5)
```
